### ISSUE TITLE
wrong answers

### ISSUE THREAD

**Issue by sharan21** [tamirlan1/Deeplearning.ai#2]
Some of these answers are wrong, and will confuse people

**Comment by AhmedAbdel-Aal** [comment]
I agree, Question 3,4,9  in week 2 quiz are wrong.

**Comment by mskhan793** [comment]
Part 6 should be True. Please, rectify it.

**Comment by tamirlan1** [comment]
Originally I've created this just to store my answers, but looks like many people are using these answers now.

I've made several changes, and merged some of your pull requests. If you see more issues, please submit pull requests, will try to timely review them.

Thanks for your inputs!
